name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.4

      - name: Install packages
        run: flutter pub get

      - name: Linter
        run: flutter analyze

      - name: Test
        run: flutter test
